//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3Net_E2_Server.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T3Net_E2_Server.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; Please enter a username before you enter: .
        /// </summary>
        internal static string CHAT_ASKUSERNAME {
            get {
                return ResourceManager.GetString("CHAT_ASKUSERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; See you next time {0}!.
        /// </summary>
        internal static string CHAT_BYEMSG {
            get {
                return ResourceManager.GetString("CHAT_BYEMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; [Type #quit to leave this server]
        ///&gt;&gt; [Type #list to list the users in the server]
        ///&gt;&gt; Enjoy yourself!.
        /// </summary>
        internal static string CHAT_COMMANDS {
            get {
                return ResourceManager.GetString("CHAT_COMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; Nice! Your assigned username will be {0}.
        /// </summary>
        internal static string CHAT_GOAHEAD {
            get {
                return ResourceManager.GetString("CHAT_GOAHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; {0} joined the room!.
        /// </summary>
        internal static string CHAT_JOINNOTICE {
            get {
                return ResourceManager.GetString("CHAT_JOINNOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; {0} left the room....
        /// </summary>
        internal static string CHAT_LEFTNOTICE {
            get {
                return ResourceManager.GetString("CHAT_LEFTNOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; The following users are connected to this server .
        /// </summary>
        internal static string CHAT_LIST {
            get {
                return ResourceManager.GetString("CHAT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  &gt;&gt; .
        /// </summary>
        internal static string CHAT_MSGSEPARATOR {
            get {
                return ResourceManager.GetString("CHAT_MSGSEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; Users with same username connecting from the same ip are not allowed. Try again please!.
        /// </summary>
        internal static string CHAT_MULTIPLEUSERSKICKED {
            get {
                return ResourceManager.GetString("CHAT_MULTIPLEUSERSKICKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; C&apos;mon don&apos;t be shy... give us a name.
        /// </summary>
        internal static string CHAT_REASKUSERNAME {
            get {
                return ResourceManager.GetString("CHAT_REASKUSERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -------------------------
        /// [SharpChat Server v1.0]
        ///-------------------------.
        /// </summary>
        internal static string CHAT_WELCOME {
            get {
                return ResourceManager.GetString("CHAT_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; Exception while on routine with client {0}.
        /// </summary>
        internal static string SRV_EXCEPTION {
            get {
                return ResourceManager.GetString("SRV_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; {0} issued a #list command.
        /// </summary>
        internal static string SRV_LISTCOMMAND {
            get {
                return ResourceManager.GetString("SRV_LISTCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; {0} issued a #quit command.
        /// </summary>
        internal static string SRV_QUITCOMMAND {
            get {
                return ResourceManager.GetString("SRV_QUITCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; SocketException: {0}.
        /// </summary>
        internal static string SRV_SOCKETEXCEPTION {
            get {
                return ResourceManager.GetString("SRV_SOCKETEXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; Client {0} connected at port {1}.
        /// </summary>
        internal static string SRV_USERCONNECT {
            get {
                return ResourceManager.GetString("SRV_USERCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; Client {0} disconnected from port {1}.
        /// </summary>
        internal static string SRV_USERDISCONNECT {
            get {
                return ResourceManager.GetString("SRV_USERDISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; Usermsg from {0} &gt;&gt; {1} .
        /// </summary>
        internal static string SRV_USERSAID {
            get {
                return ResourceManager.GetString("SRV_USERSAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; Welcome to SharpChat Server v1.0, you are currently listening on port nº {0}.
        /// </summary>
        internal static string SRV_WELCOME {
            get {
                return ResourceManager.GetString("SRV_WELCOME", resourceCulture);
            }
        }
    }
}
